### ISSUE TITLE
decoding breaks when type is an alias of string

### ISSUE THREAD

**Issue by hsanjuan** [whyrusleeping/cbor#10]
Decoding something with a `peer.ID` in it breaks as it seems to assume the destination type is string. Other codecs like msgpack work.

```go
package main

import (
	"bytes"
	"fmt"
	"log"

	peer "github.com/libp2p/go-libp2p-peer"
	cbor "github.com/multiformats/go-multicodec/cbor"
)

type myType struct {
	P peer.ID
}

func (mt myType) String() string {
	return mt.P.Pretty()
}

func main() {
	pid, _ := peer.IDB58Decode("QmXZrtE5jQwXNqCJMfHUTQkvhQ4ZAnqMnmzFMJfLewuabc")
	obj := myType{
		P: pid,
	}

	fmt.Println(obj)

	var encbuf bytes.Buffer
	enc := cbor.Multicodec().Encoder(&encbuf)
	err := enc.Encode(obj)
	if err != nil {
		log.Fatal(err)
	}

	obj2 := myType{}
	dec := cbor.Multicodec().Decoder(&encbuf)
	err = dec.Decode(&obj2)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(obj2)
}
```

```
[14:00:12] ~/goex $ go run main.go 
QmXZrtE5jQwXNqCJMfHUTQkvhQ4ZAnqMnmzFMJfLewuabc
panic: reflect.Set: value of type string is not assignable to type peer.ID

goroutine 1 [running]:
reflect.Value.assignTo(0x5bd740, 0xc420010910, 0x98, 0x601a91, 0xb, 0x5e0f80, 0x0, 0x5bd701, 0x5bd740, 0xc420010910)
        /usr/lib64/go/1.9/src/reflect/value.go:2192 +0x3a6
reflect.Value.Set(0x5e0f80, 0xc4200108c0, 0x198, 0x5bd740, 0xc420010910, 0x98)
        /usr/lib64/go/1.9/src/reflect/value.go:1357 +0xa4
github.com/whyrusleeping/cbor/go.(*reflectValue).SetString(0xc42000c520, 0xc42001a690, 0x22, 0x600, 0xc42001a690)
        /home/hector/go/src/github.com/whyrusleeping/cbor/go/cbor.go:1069 +0x155
github.com/whyrusleeping/cbor/go.(*Decoder).decodeText(0xc42008c3c0, 0x812420, 0xc42000c520, 0x18, 0x22, 0x1, 0x0)
        /home/hector/go/src/github.com/whyrusleeping/cbor/go/cbor.go:480 +0x5fd
github.com/whyrusleeping/cbor/go.(*Decoder).innerDecodeC(0xc42008c3c0, 0x812420, 0xc42000c520, 0x78, 0x1, 0x1)
        /home/hector/go/src/github.com/whyrusleeping/cbor/go/cbor.go:358 +0x13e1
github.com/whyrusleeping/cbor/go.(*Decoder).DecodeAny(0xc42008c3c0, 0x812420, 0xc42000c520, 0x812420, 0xc42000c520)
        /home/hector/go/src/github.com/whyrusleeping/cbor/go/cbor.go:239 +0xc2
github.com/whyrusleeping/cbor/go.(*Decoder).setMapKV(0xc42008c3c0, 0x810b60, 0xc42008c410, 0x812420, 0xc42000c4c0, 0x1, 0xc42001a68e)
        /home/hector/go/src/github.com/whyrusleeping/cbor/go/cbor.go:588 +0x11d
github.com/whyrusleeping/cbor/go.(*Decoder).decodeMap(0xc42008c3c0, 0x812420, 0xc42000c480, 0x1, 0x1, 0xc420057c20, 0x44da8d)
        /home/hector/go/src/github.com/whyrusleeping/cbor/go/cbor.go:735 +0x150
github.com/whyrusleeping/cbor/go.(*Decoder).innerDecodeC(0xc42008c3c0, 0x812420, 0xc42000c480, 0xa1, 0x1, 0x1)
        /home/hector/go/src/github.com/whyrusleeping/cbor/go/cbor.go:362 +0x131b
github.com/whyrusleeping/cbor/go.(*Decoder).DecodeAny(0xc42008c3c0, 0x812420, 0xc42000c480, 0xc4200108c0, 0x16)
        /home/hector/go/src/github.com/whyrusleeping/cbor/go/cbor.go:239 +0xc2
github.com/whyrusleeping/cbor/go.(*Decoder).Decode(0xc42008c3c0, 0x5c9d00, 0xc4200108c0, 0x7, 0x7)
        /home/hector/go/src/github.com/whyrusleeping/cbor/go/cbor.go:129 +0xb3
github.com/multiformats/go-multicodec/cbor.(*decoder).Decode(0xc42000c460, 0x5c9d00, 0xc4200108c0, 0x80eba0, 0xc42000c460)
        /home/hector/go/src/github.com/multiformats/go-multicodec/cbor/cbor.go:84 +0x4f
main.main()
        /home/hector/goex/main.go:37 +0x27d
exit status 2

```

**Comment by Kubuxu** [comment]
Can you try out refmt, we will want to switch to in soon-ish: https://godoc.org/github.com/polydawn/refmt/cbor

**Comment by hsanjuan** [comment]
@Kubuxu seems to work, although it does not autogenerate altlases for me, even though docs suggest so.
